services:
  - type: web
    name: my-php-app
    env: docker
    plan: free
    repo: https://github.com/username/repo-name
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
